/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateGraphicsRouteImport } from './routes/api/generate-graphics'
import { Route as ApiGenerateDesignSystemRouteImport } from './routes/api/generate-design-system'
import { Route as ApiGenerateBriefRouteImport } from './routes/api/generate-brief'
import { Route as ApiGenerateAdImageRouteImport } from './routes/api/generate-ad-image'
import { Route as ApiGenerateAdCopyRouteImport } from './routes/api/generate-ad-copy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateGraphicsRoute = ApiGenerateGraphicsRouteImport.update({
  id: '/api/generate-graphics',
  path: '/api/generate-graphics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateDesignSystemRoute = ApiGenerateDesignSystemRouteImport.update({
  id: '/api/generate-design-system',
  path: '/api/generate-design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateBriefRoute = ApiGenerateBriefRouteImport.update({
  id: '/api/generate-brief',
  path: '/api/generate-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateAdImageRoute = ApiGenerateAdImageRouteImport.update({
  id: '/api/generate-ad-image',
  path: '/api/generate-ad-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateAdCopyRoute = ApiGenerateAdCopyRouteImport.update({
  id: '/api/generate-ad-copy',
  path: '/api/generate-ad-copy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-ad-copy': typeof ApiGenerateAdCopyRoute
  '/api/generate-ad-image': typeof ApiGenerateAdImageRoute
  '/api/generate-brief': typeof ApiGenerateBriefRoute
  '/api/generate-design-system': typeof ApiGenerateDesignSystemRoute
  '/api/generate-graphics': typeof ApiGenerateGraphicsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-ad-copy': typeof ApiGenerateAdCopyRoute
  '/api/generate-ad-image': typeof ApiGenerateAdImageRoute
  '/api/generate-brief': typeof ApiGenerateBriefRoute
  '/api/generate-design-system': typeof ApiGenerateDesignSystemRoute
  '/api/generate-graphics': typeof ApiGenerateGraphicsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-ad-copy': typeof ApiGenerateAdCopyRoute
  '/api/generate-ad-image': typeof ApiGenerateAdImageRoute
  '/api/generate-brief': typeof ApiGenerateBriefRoute
  '/api/generate-design-system': typeof ApiGenerateDesignSystemRoute
  '/api/generate-graphics': typeof ApiGenerateGraphicsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/generate-ad-copy'
    | '/api/generate-ad-image'
    | '/api/generate-brief'
    | '/api/generate-design-system'
    | '/api/generate-graphics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/generate-ad-copy'
    | '/api/generate-ad-image'
    | '/api/generate-brief'
    | '/api/generate-design-system'
    | '/api/generate-graphics'
  id:
    | '__root__'
    | '/'
    | '/api/generate-ad-copy'
    | '/api/generate-ad-image'
    | '/api/generate-brief'
    | '/api/generate-design-system'
    | '/api/generate-graphics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateAdCopyRoute: typeof ApiGenerateAdCopyRoute
  ApiGenerateAdImageRoute: typeof ApiGenerateAdImageRoute
  ApiGenerateBriefRoute: typeof ApiGenerateBriefRoute
  ApiGenerateDesignSystemRoute: typeof ApiGenerateDesignSystemRoute
  ApiGenerateGraphicsRoute: typeof ApiGenerateGraphicsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-graphics': {
      id: '/api/generate-graphics'
      path: '/api/generate-graphics'
      fullPath: '/api/generate-graphics'
      preLoaderRoute: typeof ApiGenerateGraphicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-design-system': {
      id: '/api/generate-design-system'
      path: '/api/generate-design-system'
      fullPath: '/api/generate-design-system'
      preLoaderRoute: typeof ApiGenerateDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-brief': {
      id: '/api/generate-brief'
      path: '/api/generate-brief'
      fullPath: '/api/generate-brief'
      preLoaderRoute: typeof ApiGenerateBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-ad-image': {
      id: '/api/generate-ad-image'
      path: '/api/generate-ad-image'
      fullPath: '/api/generate-ad-image'
      preLoaderRoute: typeof ApiGenerateAdImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-ad-copy': {
      id: '/api/generate-ad-copy'
      path: '/api/generate-ad-copy'
      fullPath: '/api/generate-ad-copy'
      preLoaderRoute: typeof ApiGenerateAdCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateAdCopyRoute: ApiGenerateAdCopyRoute,
  ApiGenerateAdImageRoute: ApiGenerateAdImageRoute,
  ApiGenerateBriefRoute: ApiGenerateBriefRoute,
  ApiGenerateDesignSystemRoute: ApiGenerateDesignSystemRoute,
  ApiGenerateGraphicsRoute: ApiGenerateGraphicsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
